name: Test build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log into CS registry
      run: docker login registry.crowdstrike.com --username ${{ secrets.FC_ART_USERNAME}} --password ${{ secrets.FC_ART_PASSWORD }}
    - name: Setup python requirements
      run: pip3 install -r requirements.txt
    - name: Run embed.py script
      run: python3 embed.py hello-world:latest ${{ secrets.FC_CONTAINER_URI }} embedtest:latest ABCDEFGHIJKLMNOPQRSTUVWXYZ123456-78
    - name: Verify image setup correctly
      run: docker inspect embedtest:latest | jq '.[].Config'